[project]
name = "fastMCPServer"
version = "0.1.0"
description = "you description"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=3.4.3",
    "mcp[cli]>=1.6.0",
    "python-dotenv>=1.1.1",
    "pycountry>=24.3.1",
    "httpx>=0.27.0",
]
